import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type EventItem = { id:number; title:string; start_date:string; description:string; status?:string; created_at?:string };
const japanToday = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
function utcDay(value:string) { const [year, month, day] = value.split("-").map(Number); return Date.UTC(year, month - 1, day); }
function elapsed(date:string) { return Math.max(0, Math.floor((utcDay(japanToday()) - utcDay(date)) / 86400000)); }
function anniversary(date:string) { const [year, month, day] = date.split("-").map(Number); const [nowYear, nowMonth, nowDay] = japanToday().split("-").map(Number); const observedDay = month === 2 && day === 29 && nowYear % 4 !== 0 ? 28 : day; let years = nowYear - year; if (nowMonth < month || (nowMonth === month && nowDay < observedDay)) years--; return Math.max(0, years); }

function App() {
  if (location.pathname.startsWith("/admin")) return <Admin />;
  const [events,setEvents]=useState<EventItem[]>([]); const [title,setTitle]=useState(''); const [date,setDate]=useState(''); const [description,setDescription]=useState('');
  const [mode,setMode]=useState<'days'|'years'>('days'); const [view,setView]=useState<'list'|'chart'>('list'); const [sort,setSort]=useState('new'); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
  const load=()=>fetch('/api/events').then(r=>r.json() as Promise<EventItem[]>).then(setEvents).finally(()=>setLoading(false)); useEffect(()=>{load()},[]);
  const sorted=useMemo(()=>[...events].sort((a,b)=>sort==='days' ? elapsed(b.start_date)-elapsed(a.start_date) : sort==='daysAsc' ? elapsed(a.start_date)-elapsed(b.start_date) : (b.created_at??'').localeCompare(a.created_at??'')),[events,sort]);
  async function submit(e:React.FormEvent){e.preventDefault();setMessage('');const r=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,startDate:date,description})});const d=await r.json() as { error?: string };if(!r.ok){setMessage(d.error ?? "登録に失敗しました");return}setTitle('');setDate('');setDescription('');setMessage('登録しました');load()}
  return <main><header><div><p className="eyebrow">STARTED ON</p><h1>はじまりから、今日まで。</h1><p className="lead">作品、出来事、記念日。始まった日からの時間を眺める場所。</p></div><a className="admin" href="/admin">管理</a></header>
    <section className="card form-card"><h2>新しい出来事を登録</h2><form onSubmit={submit}><div className="fields"><label>名前<input value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} placeholder="例：ポケットモンスター 赤・緑 発売" required/></label><label>始まった日<input type="date" value={date} max={japanToday()} onChange={e=>setDate(e.target.value)} required/></label></div><label>補足（任意）<input value={description} maxLength={300} onChange={e=>setDescription(e.target.value)} placeholder="例：日本での発売日"/></label><button>登録する</button>{message&&<span className="message">{message}</span>}</form></section>
    <section className="toolbar"><div className="tabs"><button className={view==='list'?'active':''} onClick={()=>setView('list')}>一覧</button><button className={view==='chart'?'active':''} onClick={()=>setView('chart')}>棒グラフ</button></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">登録が新しい順</option><option value="days">経過日数が多い順</option><option value="daysAsc">経過日数が少ない順</option></select><div className="toggle"><button className={mode==='days'?'active':''} onClick={()=>setMode('days')}>経過日数</button><button className={mode==='years'?'active':''} onClick={()=>setMode('years')}>周年</button></div></section>
    {loading?<p className="empty">読み込み中…</p>:sorted.length===0?<p className="empty">まだ登録がありません。最初の出来事を登録してみましょう。</p>:view==='chart'?<Chart events={sorted} mode={mode}/>:<div className="list">{sorted.map(x=><article className="event card" key={x.id}><div><h3>{x.title}</h3>{x.description&&<p>{x.description}</p>}<small>{x.start_date.replaceAll('-','.')}</small></div><strong>{mode==='days'?`${elapsed(x.start_date).toLocaleString()}日`:`${anniversary(x.start_date)}周年`}</strong></article>)}</div>}
  </main>
}
function Admin(){ const [events,setEvents]=useState<EventItem[]>([]); const [error,setError]=useState(""); const load=()=>fetch("/api/admin/events").then(r=>r.ok?(r.json() as Promise<EventItem[]>):Promise.reject()).then(setEvents).catch(()=>setError("Basic認証が必要です。")); useEffect(()=>{load()},[]); async function toggle(x:EventItem){await fetch(`/api/admin/events/${x.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:x.title,startDate:x.start_date,description:x.description,status:x.status==="hidden"?"published":"hidden"})});load()} async function remove(id:number){if(confirm("この投稿を削除しますか？")){await fetch(`/api/admin/events/${id}`,{method:"DELETE"});load()}} return <main><header><div><p className="eyebrow">ADMIN</p><h1>投稿を管理</h1><p className="lead">公開状態の変更と削除ができます。</p></div><a className="admin" href="/">公開画面へ</a></header>{error?<p className="empty">{error}</p>:<div className="list">{events.map(x=><article className="event card" key={x.id}><div><h3>{x.title}</h3><small>{x.start_date} · {x.status==="hidden"?"非表示":"公開中"}</small></div><div className="admin-actions"><button onClick={()=>toggle(x)}>{x.status==="hidden"?"公開":"非表示"}</button><button className="danger" onClick={()=>remove(x.id)}>削除</button></div></article>)}</div>}</main> }
function Chart({events,mode}:{events:EventItem[];mode:'days'|'years'}){const values=events.slice(0,10).map(x=>mode==='days'?elapsed(x.start_date):anniversary(x.start_date));const max=Math.max(...values,1);return <div className="chart card">{events.slice(0,10).map((x,i)=><div className="bar-row" key={x.id}><span>{x.title}</span><div className="bar-track"><div className="bar" style={{width:`${Math.max(2,values[i]/max*100)}%`}}></div></div><b>{values[i].toLocaleString()}{mode==='days'?'日':'周年'}</b></div>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
